testbed_idla: testbed.cpp bsla.cpp Lstring.hpp debug.hpp lynarr.hpp
	g++ -o testbed_idla testbed.cpp -D_IDLA
silent_testbed_idla: testbed.cpp bsla.cpp Lstring.hpp debug.hpp lynarr.hpp
	g++ -o testbed_idla testbed.cpp -D_IDLA -D_silent
testbed_trla: testbed.cpp bsla.cpp Lstring.hpp debug.hpp lynarr.hpp
	g++ -o testbed_trla testbed.cpp -D_TRLA
silent_testbed_trla: testbed.cpp bsla.cpp Lstring.hpp debug.hpp lynarr.hpp
	g++ -o testbed_trla testbed.cpp -D_TRLA -D_silent
testbed_bsla: testbed.cpp bsla.cpp Lstring.hpp debug.hpp lynarr.hpp
	g++ -o testbed_bsla testbed.cpp -D_BSLA
silent_testbed_bsla: testbed.cpp bsla.cpp Lstring.hpp debug.hpp lynarr.hpp
	g++ -o testbed_bsla testbed.cpp -D_BSLA -D_silent
bsla: bsla.cpp Lstring.hpp lynarr.hpp
	g++ -o bsla bsla.cpp -D_stand_alone
trla: trla.cpp Lstring.hpp lynarr.hpp debug.hpp
	g++ -o trla trla.cpp -D_stand_alone
